PREFIX bdr-obsprops: <https://linked.data.gov.au/dataset/bdr/obsprops/>
PREFIX schema: <https://schema.org/>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX tern: <https://w3id.org/tern/ontologies/tern/>

SELECT ?rg_uri ?rg_label (SUM(?val) AS ?total) (NOW() as ?queryRunTime)
WHERE {
    GRAPH <urn:bdr:stats> {
        ?rg sosa:isFeatureOfInterestOf [
            sosa:observedProperty ?rg_uri ;
            sosa:hasResult [schema:value ?val]
        ].
    }

    # Define category URIs to labels mapping
    BIND(IF(?rg_uri = bdr-obsprops:DatasetsCount, "Datasets",
         IF(?rg_uri = bdr-obsprops:OccurrencesCount, "Occurrences",
         IF(?rg_uri = bdr-obsprops:SubmissionCount, "Submissions",
         IF(?rg_uri = bdr-obsprops:BiodiversityRecordsCount, "BiodiversityRecords",
         IF(?rg_uri = bdr-obsprops:SiteCount, "Sites",
         IF(?rg_uri = bdr-obsprops:SiteVisitCount, "SiteVisits",
         IF(?rg_uri = bdr-obsprops:SurveyCount, "Surveys",
         IF(?rg_uri = bdr-obsprops:SamplesCount, "Samples",
         IF(?rg_uri = bdr-obsprops:SamplingsCount, "Samplings",
         IF(?rg_uri = bdr-obsprops:ObservationsCount, "Observations",
         "Unknown")))))))))) AS ?rg_label
    )
    BIND(
         IF(?rg_uri = bdr-obsprops:DatasetsCount, 1,
         IF(?rg_uri = bdr-obsprops:OccurrencesCount, 3,
         IF(?rg_uri = bdr-obsprops:SubmissionCount, 2,
         IF(?rg_uri = bdr-obsprops:BiodiversityRecordsCount, 4,
         IF(?rg_uri = bdr-obsprops:SiteCount, 5,
         IF(?rg_uri = bdr-obsprops:SiteVisitCount, 6,
         IF(?rg_uri = bdr-obsprops:SurveyCount, 7,
         IF(?rg_uri = bdr-obsprops:SamplesCount, 8,
         IF(?rg_uri = bdr-obsprops:SamplingsCount, 9,
         IF(?rg_uri = bdr-obsprops:ObservationsCount, 10,
         11)))))))))) AS ?sortOrder                   
    )
}
GROUP BY ?rg_label ?rg_uri ?sortOrder
ORDER BY ?sortOrder